module.exports = {
  apps: [
    {
      name: "predict-loop",
      cwd: __dirname,
      script: "scripts/predict_loop.sh",
      interpreter: "/bin/bash",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: false,
      env: {
        TZ: "America/New_York",
        PYTHONUNBUFFERED: "1",
        PREDICT_SLEEP_SECONDS: process.env.PREDICT_SLEEP_SECONDS || "30",
        PREDICT_TIMEOUT_SECONDS: process.env.PREDICT_TIMEOUT_SECONDS || "120",
        PREDICT_ALPHA_RULES:
          process.env.PREDICT_ALPHA_RULES ||
          "baseline_router_v2,baseline_router_v1_plus_sparse_combo,baseline_current",
      },
      out_file: "logs/pm2-predict-loop.out.log",
      error_file: "logs/pm2-predict-loop.err.log",
      merge_logs: true,
    },
    {
      name: "ops-loop",
      cwd: __dirname,
      script: "scripts/ops_loop.sh",
      interpreter: "/bin/bash",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: false,
      env: {
        TZ: "America/New_York",
        PYTHONUNBUFFERED: "1",
        OPS_SLEEP_SECONDS: process.env.OPS_SLEEP_SECONDS || "300",
        OPS_TIMEOUT_SECONDS: process.env.OPS_TIMEOUT_SECONDS || "300",
      },
      out_file: "logs/pm2-ops-loop.out.log",
      error_file: "logs/pm2-ops-loop.err.log",
      merge_logs: true,
    },
    {
      name: "settlement-loop",
      cwd: __dirname,
      script: "scripts/settlement_loop.sh",
      interpreter: "/bin/bash",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: false,
      env: {
        TZ: "America/New_York",
        PYTHONUNBUFFERED: "1",
        SETTLEMENT_SLEEP_SECONDS: process.env.SETTLEMENT_SLEEP_SECONDS || "30",
        SETTLEMENT_TIMEOUT_SECONDS: process.env.SETTLEMENT_TIMEOUT_SECONDS || "120",
        PROVISIONAL_PRICE_THRESHOLD: process.env.PROVISIONAL_PRICE_THRESHOLD || "0.90",
        PROVISIONAL_CONFIRMATIONS: process.env.PROVISIONAL_CONFIRMATIONS || "2",
      },
      out_file: "logs/pm2-settlement-loop.out.log",
      error_file: "logs/pm2-settlement-loop.err.log",
      merge_logs: true,
    },
    {
      name: "dashboard",
      cwd: __dirname,
      script: ".venv/bin/python",
      args: "-u src/dashboard.py",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: false,
      env: {
        TZ: "America/New_York",
        PYTHONUNBUFFERED: "1",
      },
      out_file: "logs/pm2-dashboard.out.log",
      error_file: "logs/pm2-dashboard.err.log",
      merge_logs: true,
    },
    {
      name: "research-loop",
      cwd: __dirname,
      script: "scripts/research_loop.sh",
      interpreter: "/bin/bash",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 15000,
      time: false,
      env: {
        TZ: "America/New_York",
        PYTHONUNBUFFERED: "1",
        RESEARCH_SLEEP_SECONDS: process.env.RESEARCH_SLEEP_SECONDS || "3600",
        RESEARCH_TIMEOUT_SECONDS: process.env.RESEARCH_TIMEOUT_SECONDS || "1800",
        RESEARCH_BASELINE: process.env.RESEARCH_BASELINE || "production_baseline",
        RESEARCH_CHALLENGER: process.env.RESEARCH_CHALLENGER || "deepseek_v3",
        RESEARCH_DAYS: process.env.RESEARCH_DAYS || "3",
        RESEARCH_WARM_UP: process.env.RESEARCH_WARM_UP || "80",
        RESEARCH_FOLDS: process.env.RESEARCH_FOLDS || "2",
        RESEARCH_BET_SIZE: process.env.RESEARCH_BET_SIZE || "75",
        RESEARCH_MIN_EDGE: process.env.RESEARCH_MIN_EDGE || "0.05",
        RESEARCH_MAX_EVAL_CONTEXTS: process.env.RESEARCH_MAX_EVAL_CONTEXTS || "12",
      },
      out_file: "logs/pm2-research-loop.out.log",
      error_file: "logs/pm2-research-loop.err.log",
      merge_logs: true,
    },
    {
      name: "coach-loop",
      cwd: __dirname,
      script: "scripts/coach_loop.sh",
      interpreter: "/bin/bash",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 10000,
      time: false,
      env: {
        TZ: "America/New_York",
        PYTHONUNBUFFERED: "1",
        COACH_SLEEP_SECONDS: process.env.COACH_SLEEP_SECONDS || "300",
        COACH_TIMEOUT_SECONDS: process.env.COACH_TIMEOUT_SECONDS || "180",
      },
      out_file: "logs/pm2-coach-loop.out.log",
      error_file: "logs/pm2-coach-loop.err.log",
      merge_logs: true,
    },
  ],
};
